site_name: Cheatsheets
site_url: https://cheat.titov.spb.ru
nav:
  - Home: index.md
  - Content:
    - 'Ansible': ansible/index.md
    - 'Containers': container/index.md
    - 'Git': git/index.md
    - 'K8S': k8s/index.md
    - 'Linux': linux/index.md
  - Dev:
    - 'C#': C#101/index.md

docs_dir: 'docs'
theme: readthedocs
